name: ratbc
version: 0.1.0
category: game
license: MIT

extra-source-files:
  - README.md

dependencies:
  - base
  - binary
  - optparse-applicative
  - bytestring
  - split
  - containers
  - filepath
  - directory
  - prettyprinter
  - array
  - mtl

source-dirs:
  - src

executables:
  ratbc-disasm:
    main: ratbc-disasm.hs
    
  ratbc-asm:
    main: ratbc-asm.hs

  ratbc-strip:
    main: ratbc-strip.hs
