name: ratbc
version: 0.1.0
category: game
license: MIT

extra-source-files:
  - README.md

dependencies:
  - base
  - binary
  - optparse-applicative
  - bytestring
  - split
  - containers

source-dirs:
  - src

executables:
  ratbc-disasm:
    main: ratbc-disasm.hs
