name: ratbc
version: 0.1.0
category: game
license: MIT

extra-source-files:
  - README.md

dependencies:
  - base
  - binary
  - optparse-applicative
  - bytestring
  - split
  - containers
  - filepath
  - directory
  - prettyprinter
  - array
  - mtl
  - fgl
  - graphviz
  - rev-state
  - exceptions
  - pqueue

source-dirs:
  - src

executables:
  ratbc-disasm:
    main: ratbc-disasm.hs
    
  ratbc-asm:
    main: ratbc-asm.hs

  ratbc-hl2:
    main: ratbc-hl2.hs

  ratbc-play:
    main: ratbc-play.hs
    dependencies:
      - haskeline
