name: homelab-ratkai
version: 0.1.0
category: game
license: MIT

extra-source-files:
  - README.md

dependencies:
  - base
  - z80
  - bytestring
  - filepath
  - directory

source-dirs:
  - src

executables:
  homelab-ratkai:
    main: main.hs
